export const PUBLIC_LANDING_ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  driverRegistration: "/register/driver",
  facilityRegistration: "/register/owner",
  privacy: "/privacy-policy",
  valuePropositionAnchor: "#value-proposition",
  howItWorksAnchor: "#how-it-works",
} as const;

export const PUBLIC_LANDING_TRANSLATION_KEYS = [
  "public.header.howItWorks",
  "public.header.login",
  "public.header.register",
  "public.hero.eyebrow",
  "public.hero.headline",
  "public.hero.supporting",
  "public.hero.driverCta",
  "public.hero.facilityCta",
  "public.hero.learnMore",
  "public.hero.visualLabel",
  "public.hero.participatingLocation",
  "public.hero.verifiedActivity",
  "public.value.eyebrow",
  "public.value.heading",
  "public.value.supporting",
  "public.value.driver",
  "public.value.facility",
  "public.value.verification",
  "public.value.driverSupporting",
  "public.value.facilitySupporting",
  "public.value.verificationSupporting",
  "public.value.driverBenefit1",
  "public.value.driverBenefit2",
  "public.value.driverBenefit3",
  "public.value.driverBenefit4",
  "public.value.facilityBenefit1",
  "public.value.facilityBenefit2",
  "public.value.facilityBenefit3",
  "public.value.facilityBenefit4",
  "public.value.verificationBenefit1",
  "public.value.verificationBenefit2",
  "public.value.verificationBenefit3",
  "public.value.verificationBenefit4",
  "public.value.driverCta",
  "public.value.facilityCta",
  "public.value.verificationCta",
  "public.trust.verified",
  "public.trust.facilities",
  "public.trust.professionals",
  "public.trust.visibility",
  "public.how.eyebrow",
  "public.how.heading",
  "public.how.supporting",
  "public.how.step1Title",
  "public.how.step1Supporting",
  "public.how.step2Title",
  "public.how.step2Supporting",
  "public.how.step3Title",
  "public.how.step3Supporting",
  "public.how.step4Title",
  "public.how.step4Supporting",
  "public.driver.eyebrow",
  "public.driver.heading",
  "public.driver.supporting",
  "public.driver.benefit1",
  "public.driver.benefit2",
  "public.driver.benefit3",
  "public.driver.benefit4",
  "public.driver.cta",
  "public.facility.eyebrow",
  "public.facility.heading",
  "public.facility.supporting",
  "public.facility.benefit1",
  "public.facility.benefit2",
  "public.facility.benefit3",
  "public.facility.benefitVerification",
  "public.facility.benefit4",
  "public.facility.benefit5",
  "public.facility.cta",
  "public.footer.privacy",
  "public.footer.copyright",
] as const;

export type PublicLandingTranslationKey = (typeof PUBLIC_LANDING_TRANSLATION_KEYS)[number];
