import { Link } from "wouter";
import logoPath from "@assets/cretexchange-logo-2025.png";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-card">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex justify-between items-center">
            <Link href="/" className="flex items-center gap-2">
              <img src={logoPath} alt="CreteXchange Logo" className="h-12 w-12" />
              <span className="text-xl font-bold">
                Crete<span className="text-orange-500">X</span>change
              </span>
            </Link>
            <Link href="/login">
              <button className="px-4 py-2 text-sm font-medium text-primary hover:text-primary/80">
                Sign In
              </button>
            </Link>
          </div>
        </div>
      </header>

      {/* Privacy Policy Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="prose prose-slate dark:prose-invert max-w-none">
          <h1>Privacy Policy</h1>
          <p className="text-muted-foreground">Last updated: October 30, 2025</p>
          
          <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          
          <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
          
          <h2>Interpretation and Definitions</h2>
          <h3>Interpretation</h3>
          <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          
          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Application</strong> refers to CreteXchange, the software program provided by the Company.</li>
            <li><strong>Business</strong>, for the purpose of CCPA/CPRA, refers to the Company as the legal entity that collects Consumers' personal information and determines the purposes and means of the processing of Consumers' personal information, or on behalf of which such information is collected and that alone, or jointly with others, determines the purposes and means of the processing of consumers' personal information, that does business in the State of California.</li>
            <li><strong>CCPA</strong> and/or <strong>CPRA</strong> refers to the California Consumer Privacy Act (the "CCPA") as amended by the California Privacy Rights Act of 2020 (the "CPRA").</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to V8 Industries LLC, 11445 Mansfield Dr, Frisco, TX 75035.</li>
            <li><strong>Consumer</strong>, for the purpose of the CCPA/CPRA, means a natural person who is a California resident.</li>
            <li><strong>Country</strong> refers to: Texas, United States</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual. For the purposes of the CCPA/CPRA, Personal Data means any information that identifies, relates to, describes or is capable of being associated with, or could reasonably be linked, directly or indirectly, with You.</li>
            <li><strong>Service</strong> refers to the Application.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2>Collecting and Using Your Personal Data</h2>
          <h3>Types of Data Collected</h3>
          
          <h4>Personal Data</h4>
          <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Bank account and payment information</li>
            <li>Usage Data</li>
          </ul>

          <h4>Usage Data</h4>
          <p>Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

          <h4>Information Collected while Using the Application</h4>
          <p>While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>
          <ul>
            <li>Information regarding your location</li>
            <li>Pictures and other information from your Device's camera and photo library</li>
          </ul>
          <p>We use this information to provide features of Our Service, to improve and customize Our Service. You can enable or disable access to this information at any time, through Your Device settings.</p>

          <h3>Use of Your Personal Data</h3>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul>
            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
            <li><strong>To manage Your Account</strong> and registration as a user of the Service.</li>
            <li><strong>For the performance of a contract</strong> for products, items or services You have purchased.</li>
            <li><strong>To contact You</strong> regarding updates or informative communications related to the functionalities, products or contracted services.</li>
            <li><strong>To manage Your requests</strong> to Us.</li>
            <li><strong>For business transfers</strong> in connection with any merger, sale of Company assets, or acquisition.</li>
            <li><strong>For other purposes</strong> such as data analysis, identifying usage trends, and improving our Service.</li>
          </ul>

          <h3>Sharing of Your Personal Data</h3>
          <p>We may share Your personal information with:</p>
          <ul>
            <li><strong>Service Providers:</strong> Including Stripe for payment processing, Google Cloud for storage, and Google Maps for location services.</li>
            <li><strong>For business transfers</strong> in connection with any merger or acquisition.</li>
            <li><strong>With Your consent</strong> for any other purpose.</li>
          </ul>

          <h3>Retention of Your Personal Data</h3>
          <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>

          <h3>Security of Your Personal Data</h3>
          <p>The security of Your Personal Data is important to Us. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

          <h2>CCPA/CPRA Privacy Notice (California Privacy Rights)</h2>
          <p>This privacy notice section for California residents supplements the information contained in Our Privacy Policy and applies solely to all visitors, users, and others who reside in the State of California.</p>

          <h3>Categories of Personal Information Collected</h3>
          <p>We collect information that identifies, relates to, describes, references, is capable of being associated with, or could reasonably be linked with California residents. The following categories may be collected:</p>
          <ul>
            <li><strong>Category A: Identifiers</strong> - Name, email address, postal address, phone number, account name, IP address. <em>Collected: Yes</em></li>
            <li><strong>Category B: California Customer Records</strong> - Name, address, telephone number, bank account number, payment information. <em>Collected: Yes</em></li>
            <li><strong>Category F: Internet Activity</strong> - Interaction with our Service. <em>Collected: Yes</em></li>
            <li><strong>Category G: Geolocation Data</strong> - Approximate physical location. <em>Collected: Yes</em></li>
            <li><strong>Category L: Sensitive Personal Information</strong> - Account login and password, geolocation data. <em>Collected: Yes</em></li>
          </ul>

          <h3>Your California Privacy Rights</h3>
          <p>California residents have the right to:</p>
          <ul>
            <li>Know what personal information is collected, used, shared or sold</li>
            <li>Delete personal information held by businesses</li>
            <li>Opt-out of sale or sharing of personal information</li>
            <li>Non-discrimination for exercising CCPA rights</li>
            <li>Correct inaccurate personal information</li>
            <li>Limit use and disclosure of sensitive personal information</li>
          </ul>

          <h3>How to Exercise Your Rights</h3>
          <p>To exercise your CCPA/CPRA rights, please contact us at the information provided below. We will verify your identity before processing your request.</p>

          <h2>Children's Privacy</h2>
          <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>

          <h2>Changes to this Privacy Policy</h2>
          <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.</p>
          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

          <h2>Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul>
            <li>By visiting our website</li>
            <li>By mail: V8 Industries LLC, 11445 Mansfield Dr, Frisco, TX 75035</li>
          </ul>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border bg-card mt-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="text-center text-sm text-muted-foreground">
            <p>&copy; 2025 V8 Industries LLC. All rights reserved.</p>
            <div className="mt-2 space-x-4">
              <Link href="/privacy-policy" className="hover:text-primary">
                Privacy Policy
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
